/*
 * This source file was generated by the Gradle 'init' task
 */
package be.kuleuven;

public class App {

    public static void main(String[] args) {
        System.out.println("Nothing to see here, use the Tests");
    }

}
